import './App.css';
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import docker from "./data/docker.png";
import python from "./data/python.png";
import flutter from "./data/flutter.png";
import google from "./data/googlecloud.png";
import react from "./data/react.png";
import spring from "./data/springboot.png";
import csharp from "./data/csharp.png";
import chessscan from "./data/chessscan.png";
import avatar from './data/avatar.png'
import tensor from './data/tensorflow.png'
import React, { useState } from 'react';

function App() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      {/* <Head>
        <title>Felix Valor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className='bg-white px-10 dark:bg-gray-800'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Felix Valor</h1>
            <ul className='flex items-center'>
              <li>
                <a className='bg-gradient-to-r from-green-600 to-lime-400 text-white px-4 py-2 rounded-md ml-8 cursor-pointer' href='CV - Felix Valor Escribano.pdf' download>
                  Download my CV
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-4xl text-lime-500 font-medium'>Felix Valor</h2>
            <h3 className='text-2xl py-2 dark:text-white'>Software developer</h3>
            <p className='text-md py-5 leading-7 dark:text-white'>Hi I'm Felix, I'm a software developer, I like to find new challenges and learn as much as I can from them </p>
          </div>
          <div className='text-6xl flex justify-center dark:text-white'>
            <a href='https://www.linkedin.com/in/felix-valor/' className='px-5'><AiFillLinkedin/></a>
            <a href='https://github.com/FelixValor' className='px-5'><AiFillGithub/></a>
          </div>
          <div className='relative mx-auto bg-white rounded-full w-80 h-80 mt-20 mb-4'>
            <img src={avatar}/>
          </div>
        </section>
        <section>
            <div>
              <h3 className='text-2xl py-2 text-center dark:text-white'>Technologies that I mainly use</h3>
            </div>
            
            <div className="lg:grid gap-6">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gray-700 col-start-1">
              <img src={python} width={120} className="mx-auto" />
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700 col-start-2">
              <img src={tensor} width={120} className="mx-auto" />
              
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700 col-start-3">
              <img src={docker} width={120} className="mx-auto" />
              
            </div>
            <div className="text-center shadow-lg pt-12 pr-8 rounded-xl my-10  dark:bg-gray-700 col-start-4">
              <img src={flutter} width={140} className="mx-auto" />
              
            </div>
            <div className="text-center shadow-lg pt-7 pb-6 rounded-xl my-10 dark:bg-gray-700 col-start-5">
              <img src={google} width={200} className="mx-auto" />
              
            </div>
            <div className="text-center shadow-lg pt-3 rounded-xl my-10 dark:bg-gray-700 col-start-2">
              <img src={csharp} width={180} className="mx-auto" />
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700 col-start-3">
              <img src={react} width={120} className="mx-auto" />
              
            </div>
            <div className="text-center shadow-lg pt-12 rounded-xl my-10 dark:bg-gray-700 col-start-4">
              <img src={spring} width={185} className="mx-auto" />
              
            </div>
          </div>
          </section>
          <div>
              <h3 className='text-2xl py-2 text-center dark:text-white'>My Projects</h3>
              <div className="text-center pt-10 flex">
              <a href='https://play.google.com/store/apps/details?id=com.fvalor.chess_scan' className='mx-auto'><img src={chessscan} width={140} className="rounded-xl" /></a>
              
            </div>
              <br/>
              <br/>
              <br/>
              <br/>
            </div>
      </main>
    </div>
  );
}

export default App;
